name: dbt_test
version: 1.0.0
config-version: 2
profile: normalize

models:
  dbt_test:
    staging:
      +schema: staging
    data_marts:
      +materialized: table
      okr:
        +schema: dm_okr
